// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && with_ebpf

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	CgroupStorageMapCgroupBypassIpv4            = "cgroup_bypass_ipv4"
	CgroupStorageMapCgroupBypassIpv6            = "cgroup_bypass_ipv6"
	CgroupStorageMapCgroupBypassPort            = "cgroup_bypass_port"
	CgroupStorageMapCgroupControl               = "cgroup_control"
	CgroupStorageMapCgroupHostIpv4              = "cgroup_host_ipv4"
	CgroupStorageMapCgroupHostIpv6              = "cgroup_host_ipv6"
	CgroupStorageMapCgroupSocketBypass          = "cgroup_socket_bypass"
	CgroupStorageMapCgroupTcpRedirect           = "cgroup_tcp_redirect"
	CgroupStorageMapCgroupUdpFlow               = "cgroup_udp_flow"
	CgroupStorageMapCgroupUdpPeer               = "cgroup_udp_peer"
	CgroupStorageMapCgroupUdpRecovery           = "cgroup_udp_recovery"
	CgroupStorageMapCgroupUdpRedirect           = "cgroup_udp_redirect"
	CgroupStorageMapCgroupUdpSocketStorage      = "cgroup_udp_socket_storage"
	CgroupStorageMapCgroupUdpToken              = "cgroup_udp_token"
	CgroupStorageMapCgroupUidPolicy             = "cgroup_uid_policy"
	CgroupStorageProgSbEbpfConn4Cookie          = "sb_ebpf_conn4_cookie"
	CgroupStorageProgSbEbpfConn4CookieTcp       = "sb_ebpf_conn4_cookie_tcp"
	CgroupStorageProgSbEbpfConn4CookieUdp       = "sb_ebpf_conn4_cookie_udp"
	CgroupStorageProgSbEbpfConn6Cookie          = "sb_ebpf_conn6_cookie"
	CgroupStorageProgSbEbpfConn6CookieTcp       = "sb_ebpf_conn6_cookie_tcp"
	CgroupStorageProgSbEbpfConn6CookieUdp       = "sb_ebpf_conn6_cookie_udp"
	CgroupStorageProgSbEbpfConn6MappedCookie    = "sb_ebpf_conn6_mapped_cookie"
	CgroupStorageProgSbEbpfConn6MappedCookieTcp = "sb_ebpf_conn6_mapped_cookie_tcp"
	CgroupStorageProgSbEbpfConn6MappedCookieUdp = "sb_ebpf_conn6_mapped_cookie_udp"
	CgroupStorageProgSbEbpfRelCookie            = "sb_ebpf_rel_cookie"
	CgroupStorageProgSbEbpfUdp4Cookie           = "sb_ebpf_udp4_cookie"
	CgroupStorageProgSbEbpfUdp6Cookie           = "sb_ebpf_udp6_cookie"
	CgroupStorageProgSbEbpfUdp6MappedCookie     = "sb_ebpf_udp6_mapped_cookie"
	CgroupStorageProgSbEbpfUrcv4C               = "sb_ebpf_urcv4_c"
	CgroupStorageProgSbEbpfUrcv6C               = "sb_ebpf_urcv6_c"
	CgroupStorageProgSbEbpfUrcv6MappedC         = "sb_ebpf_urcv6_mapped_c"
)

// LoadCgroupStorage returns the embedded CollectionSpec for CgroupStorage.
func LoadCgroupStorage() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CgroupStorageBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load CgroupStorage: %w", err)
	}

	return spec, err
}

// LoadCgroupStorageObjects loads CgroupStorage and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CgroupStorageObjects
//	*CgroupStoragePrograms
//	*CgroupStorageMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCgroupStorageObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCgroupStorage()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CgroupStorageSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupStorageSpecs struct {
	CgroupStorageProgramSpecs
	CgroupStorageMapSpecs
	CgroupStorageVariableSpecs
}

// CgroupStorageProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupStorageProgramSpecs struct {
	SbEbpfConn4Cookie          *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn4_cookie"`
	SbEbpfConn4CookieTcp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn4_cookie_tcp"`
	SbEbpfConn4CookieUdp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn4_cookie_udp"`
	SbEbpfConn6Cookie          *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_cookie"`
	SbEbpfConn6CookieTcp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_cookie_tcp"`
	SbEbpfConn6CookieUdp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_cookie_udp"`
	SbEbpfConn6MappedCookie    *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_mapped_cookie"`
	SbEbpfConn6MappedCookieTcp *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_mapped_cookie_tcp"`
	SbEbpfConn6MappedCookieUdp *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_mapped_cookie_udp"`
	SbEbpfRelCookie            *ebpf.ProgramSpec `ebpf:"sb_ebpf_rel_cookie"`
	SbEbpfUdp4Cookie           *ebpf.ProgramSpec `ebpf:"sb_ebpf_udp4_cookie"`
	SbEbpfUdp6Cookie           *ebpf.ProgramSpec `ebpf:"sb_ebpf_udp6_cookie"`
	SbEbpfUdp6MappedCookie     *ebpf.ProgramSpec `ebpf:"sb_ebpf_udp6_mapped_cookie"`
	SbEbpfUrcv4C               *ebpf.ProgramSpec `ebpf:"sb_ebpf_urcv4_c"`
	SbEbpfUrcv6C               *ebpf.ProgramSpec `ebpf:"sb_ebpf_urcv6_c"`
	SbEbpfUrcv6MappedC         *ebpf.ProgramSpec `ebpf:"sb_ebpf_urcv6_mapped_c"`
}

// CgroupStorageMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupStorageMapSpecs struct {
	CgroupBypassIpv4       *ebpf.MapSpec `ebpf:"cgroup_bypass_ipv4"`
	CgroupBypassIpv6       *ebpf.MapSpec `ebpf:"cgroup_bypass_ipv6"`
	CgroupBypassPort       *ebpf.MapSpec `ebpf:"cgroup_bypass_port"`
	CgroupControl          *ebpf.MapSpec `ebpf:"cgroup_control"`
	CgroupHostIpv4         *ebpf.MapSpec `ebpf:"cgroup_host_ipv4"`
	CgroupHostIpv6         *ebpf.MapSpec `ebpf:"cgroup_host_ipv6"`
	CgroupSocketBypass     *ebpf.MapSpec `ebpf:"cgroup_socket_bypass"`
	CgroupTcpRedirect      *ebpf.MapSpec `ebpf:"cgroup_tcp_redirect"`
	CgroupUdpFlow          *ebpf.MapSpec `ebpf:"cgroup_udp_flow"`
	CgroupUdpPeer          *ebpf.MapSpec `ebpf:"cgroup_udp_peer"`
	CgroupUdpRecovery      *ebpf.MapSpec `ebpf:"cgroup_udp_recovery"`
	CgroupUdpRedirect      *ebpf.MapSpec `ebpf:"cgroup_udp_redirect"`
	CgroupUdpSocketStorage *ebpf.MapSpec `ebpf:"cgroup_udp_socket_storage"`
	CgroupUdpToken         *ebpf.MapSpec `ebpf:"cgroup_udp_token"`
	CgroupUidPolicy        *ebpf.MapSpec `ebpf:"cgroup_uid_policy"`
}

// CgroupStorageVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupStorageVariableSpecs struct {
}

// CgroupStorageObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupStorageObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupStorageObjects struct {
	CgroupStoragePrograms
	CgroupStorageMaps
	CgroupStorageVariables
}

func (o *CgroupStorageObjects) Close() error {
	return _CgroupStorageClose(
		&o.CgroupStoragePrograms,
		&o.CgroupStorageMaps,
	)
}

// CgroupStorageMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupStorageObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupStorageMaps struct {
	CgroupBypassIpv4       *ebpf.Map `ebpf:"cgroup_bypass_ipv4"`
	CgroupBypassIpv6       *ebpf.Map `ebpf:"cgroup_bypass_ipv6"`
	CgroupBypassPort       *ebpf.Map `ebpf:"cgroup_bypass_port"`
	CgroupControl          *ebpf.Map `ebpf:"cgroup_control"`
	CgroupHostIpv4         *ebpf.Map `ebpf:"cgroup_host_ipv4"`
	CgroupHostIpv6         *ebpf.Map `ebpf:"cgroup_host_ipv6"`
	CgroupSocketBypass     *ebpf.Map `ebpf:"cgroup_socket_bypass"`
	CgroupTcpRedirect      *ebpf.Map `ebpf:"cgroup_tcp_redirect"`
	CgroupUdpFlow          *ebpf.Map `ebpf:"cgroup_udp_flow"`
	CgroupUdpPeer          *ebpf.Map `ebpf:"cgroup_udp_peer"`
	CgroupUdpRecovery      *ebpf.Map `ebpf:"cgroup_udp_recovery"`
	CgroupUdpRedirect      *ebpf.Map `ebpf:"cgroup_udp_redirect"`
	CgroupUdpSocketStorage *ebpf.Map `ebpf:"cgroup_udp_socket_storage"`
	CgroupUdpToken         *ebpf.Map `ebpf:"cgroup_udp_token"`
	CgroupUidPolicy        *ebpf.Map `ebpf:"cgroup_uid_policy"`
}

func (m *CgroupStorageMaps) Close() error {
	return _CgroupStorageClose(
		m.CgroupBypassIpv4,
		m.CgroupBypassIpv6,
		m.CgroupBypassPort,
		m.CgroupControl,
		m.CgroupHostIpv4,
		m.CgroupHostIpv6,
		m.CgroupSocketBypass,
		m.CgroupTcpRedirect,
		m.CgroupUdpFlow,
		m.CgroupUdpPeer,
		m.CgroupUdpRecovery,
		m.CgroupUdpRedirect,
		m.CgroupUdpSocketStorage,
		m.CgroupUdpToken,
		m.CgroupUidPolicy,
	)
}

// CgroupStorageVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupStorageObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupStorageVariables struct {
}

// CgroupStoragePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupStorageObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupStoragePrograms struct {
	SbEbpfConn4Cookie          *ebpf.Program `ebpf:"sb_ebpf_conn4_cookie"`
	SbEbpfConn4CookieTcp       *ebpf.Program `ebpf:"sb_ebpf_conn4_cookie_tcp"`
	SbEbpfConn4CookieUdp       *ebpf.Program `ebpf:"sb_ebpf_conn4_cookie_udp"`
	SbEbpfConn6Cookie          *ebpf.Program `ebpf:"sb_ebpf_conn6_cookie"`
	SbEbpfConn6CookieTcp       *ebpf.Program `ebpf:"sb_ebpf_conn6_cookie_tcp"`
	SbEbpfConn6CookieUdp       *ebpf.Program `ebpf:"sb_ebpf_conn6_cookie_udp"`
	SbEbpfConn6MappedCookie    *ebpf.Program `ebpf:"sb_ebpf_conn6_mapped_cookie"`
	SbEbpfConn6MappedCookieTcp *ebpf.Program `ebpf:"sb_ebpf_conn6_mapped_cookie_tcp"`
	SbEbpfConn6MappedCookieUdp *ebpf.Program `ebpf:"sb_ebpf_conn6_mapped_cookie_udp"`
	SbEbpfRelCookie            *ebpf.Program `ebpf:"sb_ebpf_rel_cookie"`
	SbEbpfUdp4Cookie           *ebpf.Program `ebpf:"sb_ebpf_udp4_cookie"`
	SbEbpfUdp6Cookie           *ebpf.Program `ebpf:"sb_ebpf_udp6_cookie"`
	SbEbpfUdp6MappedCookie     *ebpf.Program `ebpf:"sb_ebpf_udp6_mapped_cookie"`
	SbEbpfUrcv4C               *ebpf.Program `ebpf:"sb_ebpf_urcv4_c"`
	SbEbpfUrcv6C               *ebpf.Program `ebpf:"sb_ebpf_urcv6_c"`
	SbEbpfUrcv6MappedC         *ebpf.Program `ebpf:"sb_ebpf_urcv6_mapped_c"`
}

func (p *CgroupStoragePrograms) Close() error {
	return _CgroupStorageClose(
		p.SbEbpfConn4Cookie,
		p.SbEbpfConn4CookieTcp,
		p.SbEbpfConn4CookieUdp,
		p.SbEbpfConn6Cookie,
		p.SbEbpfConn6CookieTcp,
		p.SbEbpfConn6CookieUdp,
		p.SbEbpfConn6MappedCookie,
		p.SbEbpfConn6MappedCookieTcp,
		p.SbEbpfConn6MappedCookieUdp,
		p.SbEbpfRelCookie,
		p.SbEbpfUdp4Cookie,
		p.SbEbpfUdp6Cookie,
		p.SbEbpfUdp6MappedCookie,
		p.SbEbpfUrcv4C,
		p.SbEbpfUrcv6C,
		p.SbEbpfUrcv6MappedC,
	)
}

func _CgroupStorageClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cgroup_storage_bpfel.o
var _CgroupStorageBytes []byte
