// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && with_ebpf

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	CgroupCoarseMapCgroupBypassIpv4            = "cgroup_bypass_ipv4"
	CgroupCoarseMapCgroupBypassIpv6            = "cgroup_bypass_ipv6"
	CgroupCoarseMapCgroupBypassPort            = "cgroup_bypass_port"
	CgroupCoarseMapCgroupControl               = "cgroup_control"
	CgroupCoarseMapCgroupHostIpv4              = "cgroup_host_ipv4"
	CgroupCoarseMapCgroupHostIpv6              = "cgroup_host_ipv6"
	CgroupCoarseMapCgroupSocketBypass          = "cgroup_socket_bypass"
	CgroupCoarseMapCgroupTcpRedirect           = "cgroup_tcp_redirect"
	CgroupCoarseMapCgroupUdpFlow               = "cgroup_udp_flow"
	CgroupCoarseMapCgroupUdpPeer               = "cgroup_udp_peer"
	CgroupCoarseMapCgroupUdpRecovery           = "cgroup_udp_recovery"
	CgroupCoarseMapCgroupUdpRedirect           = "cgroup_udp_redirect"
	CgroupCoarseMapCgroupUdpToken              = "cgroup_udp_token"
	CgroupCoarseMapCgroupUidPolicy             = "cgroup_uid_policy"
	CgroupCoarseProgSbEbpfConn4Cookie          = "sb_ebpf_conn4_cookie"
	CgroupCoarseProgSbEbpfConn4CookieTcp       = "sb_ebpf_conn4_cookie_tcp"
	CgroupCoarseProgSbEbpfConn4CookieUdp       = "sb_ebpf_conn4_cookie_udp"
	CgroupCoarseProgSbEbpfConn6Cookie          = "sb_ebpf_conn6_cookie"
	CgroupCoarseProgSbEbpfConn6CookieTcp       = "sb_ebpf_conn6_cookie_tcp"
	CgroupCoarseProgSbEbpfConn6CookieUdp       = "sb_ebpf_conn6_cookie_udp"
	CgroupCoarseProgSbEbpfConn6MappedCookie    = "sb_ebpf_conn6_mapped_cookie"
	CgroupCoarseProgSbEbpfConn6MappedCookieTcp = "sb_ebpf_conn6_mapped_cookie_tcp"
	CgroupCoarseProgSbEbpfConn6MappedCookieUdp = "sb_ebpf_conn6_mapped_cookie_udp"
	CgroupCoarseProgSbEbpfRelCookie            = "sb_ebpf_rel_cookie"
	CgroupCoarseProgSbEbpfUdp4Cookie           = "sb_ebpf_udp4_cookie"
	CgroupCoarseProgSbEbpfUdp6Cookie           = "sb_ebpf_udp6_cookie"
	CgroupCoarseProgSbEbpfUdp6MappedCookie     = "sb_ebpf_udp6_mapped_cookie"
	CgroupCoarseProgSbEbpfUrcv4C               = "sb_ebpf_urcv4_c"
	CgroupCoarseProgSbEbpfUrcv6C               = "sb_ebpf_urcv6_c"
	CgroupCoarseProgSbEbpfUrcv6MappedC         = "sb_ebpf_urcv6_mapped_c"
)

// LoadCgroupCoarse returns the embedded CollectionSpec for CgroupCoarse.
func LoadCgroupCoarse() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CgroupCoarseBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load CgroupCoarse: %w", err)
	}

	return spec, err
}

// LoadCgroupCoarseObjects loads CgroupCoarse and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CgroupCoarseObjects
//	*CgroupCoarsePrograms
//	*CgroupCoarseMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCgroupCoarseObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCgroupCoarse()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CgroupCoarseSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupCoarseSpecs struct {
	CgroupCoarseProgramSpecs
	CgroupCoarseMapSpecs
	CgroupCoarseVariableSpecs
}

// CgroupCoarseProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupCoarseProgramSpecs struct {
	SbEbpfConn4Cookie          *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn4_cookie"`
	SbEbpfConn4CookieTcp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn4_cookie_tcp"`
	SbEbpfConn4CookieUdp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn4_cookie_udp"`
	SbEbpfConn6Cookie          *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_cookie"`
	SbEbpfConn6CookieTcp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_cookie_tcp"`
	SbEbpfConn6CookieUdp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_cookie_udp"`
	SbEbpfConn6MappedCookie    *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_mapped_cookie"`
	SbEbpfConn6MappedCookieTcp *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_mapped_cookie_tcp"`
	SbEbpfConn6MappedCookieUdp *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_mapped_cookie_udp"`
	SbEbpfRelCookie            *ebpf.ProgramSpec `ebpf:"sb_ebpf_rel_cookie"`
	SbEbpfUdp4Cookie           *ebpf.ProgramSpec `ebpf:"sb_ebpf_udp4_cookie"`
	SbEbpfUdp6Cookie           *ebpf.ProgramSpec `ebpf:"sb_ebpf_udp6_cookie"`
	SbEbpfUdp6MappedCookie     *ebpf.ProgramSpec `ebpf:"sb_ebpf_udp6_mapped_cookie"`
	SbEbpfUrcv4C               *ebpf.ProgramSpec `ebpf:"sb_ebpf_urcv4_c"`
	SbEbpfUrcv6C               *ebpf.ProgramSpec `ebpf:"sb_ebpf_urcv6_c"`
	SbEbpfUrcv6MappedC         *ebpf.ProgramSpec `ebpf:"sb_ebpf_urcv6_mapped_c"`
}

// CgroupCoarseMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupCoarseMapSpecs struct {
	CgroupBypassIpv4   *ebpf.MapSpec `ebpf:"cgroup_bypass_ipv4"`
	CgroupBypassIpv6   *ebpf.MapSpec `ebpf:"cgroup_bypass_ipv6"`
	CgroupBypassPort   *ebpf.MapSpec `ebpf:"cgroup_bypass_port"`
	CgroupControl      *ebpf.MapSpec `ebpf:"cgroup_control"`
	CgroupHostIpv4     *ebpf.MapSpec `ebpf:"cgroup_host_ipv4"`
	CgroupHostIpv6     *ebpf.MapSpec `ebpf:"cgroup_host_ipv6"`
	CgroupSocketBypass *ebpf.MapSpec `ebpf:"cgroup_socket_bypass"`
	CgroupTcpRedirect  *ebpf.MapSpec `ebpf:"cgroup_tcp_redirect"`
	CgroupUdpFlow      *ebpf.MapSpec `ebpf:"cgroup_udp_flow"`
	CgroupUdpPeer      *ebpf.MapSpec `ebpf:"cgroup_udp_peer"`
	CgroupUdpRecovery  *ebpf.MapSpec `ebpf:"cgroup_udp_recovery"`
	CgroupUdpRedirect  *ebpf.MapSpec `ebpf:"cgroup_udp_redirect"`
	CgroupUdpToken     *ebpf.MapSpec `ebpf:"cgroup_udp_token"`
	CgroupUidPolicy    *ebpf.MapSpec `ebpf:"cgroup_uid_policy"`
}

// CgroupCoarseVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupCoarseVariableSpecs struct {
}

// CgroupCoarseObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupCoarseObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupCoarseObjects struct {
	CgroupCoarsePrograms
	CgroupCoarseMaps
	CgroupCoarseVariables
}

func (o *CgroupCoarseObjects) Close() error {
	return _CgroupCoarseClose(
		&o.CgroupCoarsePrograms,
		&o.CgroupCoarseMaps,
	)
}

// CgroupCoarseMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupCoarseObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupCoarseMaps struct {
	CgroupBypassIpv4   *ebpf.Map `ebpf:"cgroup_bypass_ipv4"`
	CgroupBypassIpv6   *ebpf.Map `ebpf:"cgroup_bypass_ipv6"`
	CgroupBypassPort   *ebpf.Map `ebpf:"cgroup_bypass_port"`
	CgroupControl      *ebpf.Map `ebpf:"cgroup_control"`
	CgroupHostIpv4     *ebpf.Map `ebpf:"cgroup_host_ipv4"`
	CgroupHostIpv6     *ebpf.Map `ebpf:"cgroup_host_ipv6"`
	CgroupSocketBypass *ebpf.Map `ebpf:"cgroup_socket_bypass"`
	CgroupTcpRedirect  *ebpf.Map `ebpf:"cgroup_tcp_redirect"`
	CgroupUdpFlow      *ebpf.Map `ebpf:"cgroup_udp_flow"`
	CgroupUdpPeer      *ebpf.Map `ebpf:"cgroup_udp_peer"`
	CgroupUdpRecovery  *ebpf.Map `ebpf:"cgroup_udp_recovery"`
	CgroupUdpRedirect  *ebpf.Map `ebpf:"cgroup_udp_redirect"`
	CgroupUdpToken     *ebpf.Map `ebpf:"cgroup_udp_token"`
	CgroupUidPolicy    *ebpf.Map `ebpf:"cgroup_uid_policy"`
}

func (m *CgroupCoarseMaps) Close() error {
	return _CgroupCoarseClose(
		m.CgroupBypassIpv4,
		m.CgroupBypassIpv6,
		m.CgroupBypassPort,
		m.CgroupControl,
		m.CgroupHostIpv4,
		m.CgroupHostIpv6,
		m.CgroupSocketBypass,
		m.CgroupTcpRedirect,
		m.CgroupUdpFlow,
		m.CgroupUdpPeer,
		m.CgroupUdpRecovery,
		m.CgroupUdpRedirect,
		m.CgroupUdpToken,
		m.CgroupUidPolicy,
	)
}

// CgroupCoarseVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupCoarseObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupCoarseVariables struct {
}

// CgroupCoarsePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupCoarseObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupCoarsePrograms struct {
	SbEbpfConn4Cookie          *ebpf.Program `ebpf:"sb_ebpf_conn4_cookie"`
	SbEbpfConn4CookieTcp       *ebpf.Program `ebpf:"sb_ebpf_conn4_cookie_tcp"`
	SbEbpfConn4CookieUdp       *ebpf.Program `ebpf:"sb_ebpf_conn4_cookie_udp"`
	SbEbpfConn6Cookie          *ebpf.Program `ebpf:"sb_ebpf_conn6_cookie"`
	SbEbpfConn6CookieTcp       *ebpf.Program `ebpf:"sb_ebpf_conn6_cookie_tcp"`
	SbEbpfConn6CookieUdp       *ebpf.Program `ebpf:"sb_ebpf_conn6_cookie_udp"`
	SbEbpfConn6MappedCookie    *ebpf.Program `ebpf:"sb_ebpf_conn6_mapped_cookie"`
	SbEbpfConn6MappedCookieTcp *ebpf.Program `ebpf:"sb_ebpf_conn6_mapped_cookie_tcp"`
	SbEbpfConn6MappedCookieUdp *ebpf.Program `ebpf:"sb_ebpf_conn6_mapped_cookie_udp"`
	SbEbpfRelCookie            *ebpf.Program `ebpf:"sb_ebpf_rel_cookie"`
	SbEbpfUdp4Cookie           *ebpf.Program `ebpf:"sb_ebpf_udp4_cookie"`
	SbEbpfUdp6Cookie           *ebpf.Program `ebpf:"sb_ebpf_udp6_cookie"`
	SbEbpfUdp6MappedCookie     *ebpf.Program `ebpf:"sb_ebpf_udp6_mapped_cookie"`
	SbEbpfUrcv4C               *ebpf.Program `ebpf:"sb_ebpf_urcv4_c"`
	SbEbpfUrcv6C               *ebpf.Program `ebpf:"sb_ebpf_urcv6_c"`
	SbEbpfUrcv6MappedC         *ebpf.Program `ebpf:"sb_ebpf_urcv6_mapped_c"`
}

func (p *CgroupCoarsePrograms) Close() error {
	return _CgroupCoarseClose(
		p.SbEbpfConn4Cookie,
		p.SbEbpfConn4CookieTcp,
		p.SbEbpfConn4CookieUdp,
		p.SbEbpfConn6Cookie,
		p.SbEbpfConn6CookieTcp,
		p.SbEbpfConn6CookieUdp,
		p.SbEbpfConn6MappedCookie,
		p.SbEbpfConn6MappedCookieTcp,
		p.SbEbpfConn6MappedCookieUdp,
		p.SbEbpfRelCookie,
		p.SbEbpfUdp4Cookie,
		p.SbEbpfUdp6Cookie,
		p.SbEbpfUdp6MappedCookie,
		p.SbEbpfUrcv4C,
		p.SbEbpfUrcv6C,
		p.SbEbpfUrcv6MappedC,
	)
}

func _CgroupCoarseClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cgroup_coarse_bpfel.o
var _CgroupCoarseBytes []byte
