// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && with_ebpf

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	FakeIPICMPMapFakeipIcmpControl                     = "fakeip_icmp_control"
	FakeIPICMPMapFakeipIcmpStats                       = "fakeip_icmp_stats"
	FakeIPICMPProgSingboxFakeipIcmpLocalReplyEthernet  = "singbox_fakeip_icmp_local_reply_ethernet"
	FakeIPICMPProgSingboxFakeipIcmpLocalReplyRawIp     = "singbox_fakeip_icmp_local_reply_raw_ip"
	FakeIPICMPProgSingboxFakeipIcmpSharedReplyEthernet = "singbox_fakeip_icmp_shared_reply_ethernet"
	FakeIPICMPProgSingboxFakeipIcmpSharedReplyRawIp    = "singbox_fakeip_icmp_shared_reply_raw_ip"
)

// LoadFakeIPICMP returns the embedded CollectionSpec for FakeIPICMP.
func LoadFakeIPICMP() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FakeIPICMPBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load FakeIPICMP: %w", err)
	}

	return spec, err
}

// LoadFakeIPICMPObjects loads FakeIPICMP and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FakeIPICMPObjects
//	*FakeIPICMPPrograms
//	*FakeIPICMPMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFakeIPICMPObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFakeIPICMP()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FakeIPICMPSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FakeIPICMPSpecs struct {
	FakeIPICMPProgramSpecs
	FakeIPICMPMapSpecs
	FakeIPICMPVariableSpecs
}

// FakeIPICMPProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FakeIPICMPProgramSpecs struct {
	SingboxFakeipIcmpLocalReplyEthernet  *ebpf.ProgramSpec `ebpf:"singbox_fakeip_icmp_local_reply_ethernet"`
	SingboxFakeipIcmpLocalReplyRawIp     *ebpf.ProgramSpec `ebpf:"singbox_fakeip_icmp_local_reply_raw_ip"`
	SingboxFakeipIcmpSharedReplyEthernet *ebpf.ProgramSpec `ebpf:"singbox_fakeip_icmp_shared_reply_ethernet"`
	SingboxFakeipIcmpSharedReplyRawIp    *ebpf.ProgramSpec `ebpf:"singbox_fakeip_icmp_shared_reply_raw_ip"`
}

// FakeIPICMPMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FakeIPICMPMapSpecs struct {
	FakeipIcmpControl *ebpf.MapSpec `ebpf:"fakeip_icmp_control"`
	FakeipIcmpStats   *ebpf.MapSpec `ebpf:"fakeip_icmp_stats"`
}

// FakeIPICMPVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FakeIPICMPVariableSpecs struct {
}

// FakeIPICMPObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFakeIPICMPObjects or ebpf.CollectionSpec.LoadAndAssign.
type FakeIPICMPObjects struct {
	FakeIPICMPPrograms
	FakeIPICMPMaps
	FakeIPICMPVariables
}

func (o *FakeIPICMPObjects) Close() error {
	return _FakeIPICMPClose(
		&o.FakeIPICMPPrograms,
		&o.FakeIPICMPMaps,
	)
}

// FakeIPICMPMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFakeIPICMPObjects or ebpf.CollectionSpec.LoadAndAssign.
type FakeIPICMPMaps struct {
	FakeipIcmpControl *ebpf.Map `ebpf:"fakeip_icmp_control"`
	FakeipIcmpStats   *ebpf.Map `ebpf:"fakeip_icmp_stats"`
}

func (m *FakeIPICMPMaps) Close() error {
	return _FakeIPICMPClose(
		m.FakeipIcmpControl,
		m.FakeipIcmpStats,
	)
}

// FakeIPICMPVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFakeIPICMPObjects or ebpf.CollectionSpec.LoadAndAssign.
type FakeIPICMPVariables struct {
}

// FakeIPICMPPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFakeIPICMPObjects or ebpf.CollectionSpec.LoadAndAssign.
type FakeIPICMPPrograms struct {
	SingboxFakeipIcmpLocalReplyEthernet  *ebpf.Program `ebpf:"singbox_fakeip_icmp_local_reply_ethernet"`
	SingboxFakeipIcmpLocalReplyRawIp     *ebpf.Program `ebpf:"singbox_fakeip_icmp_local_reply_raw_ip"`
	SingboxFakeipIcmpSharedReplyEthernet *ebpf.Program `ebpf:"singbox_fakeip_icmp_shared_reply_ethernet"`
	SingboxFakeipIcmpSharedReplyRawIp    *ebpf.Program `ebpf:"singbox_fakeip_icmp_shared_reply_raw_ip"`
}

func (p *FakeIPICMPPrograms) Close() error {
	return _FakeIPICMPClose(
		p.SingboxFakeipIcmpLocalReplyEthernet,
		p.SingboxFakeipIcmpLocalReplyRawIp,
		p.SingboxFakeipIcmpSharedReplyEthernet,
		p.SingboxFakeipIcmpSharedReplyRawIp,
	)
}

func _FakeIPICMPClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fakeip_icmp_bpfeb.o
var _FakeIPICMPBytes []byte
