// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && with_ebpf

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	SharedNetworkMapSharedBypassFlow        = "shared_bypass_flow"
	SharedNetworkMapSharedBypassIpv4        = "shared_bypass_ipv4"
	SharedNetworkMapSharedBypassIpv6        = "shared_bypass_ipv6"
	SharedNetworkMapSharedControl           = "shared_control"
	SharedNetworkMapSharedExcludeSourceIpv4 = "shared_exclude_source_ipv4"
	SharedNetworkMapSharedExcludeSourceIpv6 = "shared_exclude_source_ipv6"
	SharedNetworkMapSharedExcludeSourceMac  = "shared_exclude_source_mac"
	SharedNetworkMapSharedFlowByOriginal    = "shared_flow_by_original"
	SharedNetworkMapSharedFlowByToken       = "shared_flow_by_token"
	SharedNetworkMapSharedHostIpv4          = "shared_host_ipv4"
	SharedNetworkMapSharedHostIpv6          = "shared_host_ipv6"
	SharedNetworkMapSharedIncludeSourceIpv4 = "shared_include_source_ipv4"
	SharedNetworkMapSharedIncludeSourceIpv6 = "shared_include_source_ipv6"
	SharedNetworkMapSharedIncludeSourceMac  = "shared_include_source_mac"
	SharedNetworkMapSharedScratch           = "shared_scratch"
	SharedNetworkMapSharedStats             = "shared_stats"
	SharedNetworkProgSingboxSharedEgress    = "singbox_shared_egress"
	SharedNetworkProgSingboxSharedIngress   = "singbox_shared_ingress"
)

// LoadSharedNetwork returns the embedded CollectionSpec for SharedNetwork.
func LoadSharedNetwork() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SharedNetworkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SharedNetwork: %w", err)
	}

	return spec, err
}

// LoadSharedNetworkObjects loads SharedNetwork and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SharedNetworkObjects
//	*SharedNetworkPrograms
//	*SharedNetworkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSharedNetworkObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSharedNetwork()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SharedNetworkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SharedNetworkSpecs struct {
	SharedNetworkProgramSpecs
	SharedNetworkMapSpecs
	SharedNetworkVariableSpecs
}

// SharedNetworkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SharedNetworkProgramSpecs struct {
	SingboxSharedEgress  *ebpf.ProgramSpec `ebpf:"singbox_shared_egress"`
	SingboxSharedIngress *ebpf.ProgramSpec `ebpf:"singbox_shared_ingress"`
}

// SharedNetworkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SharedNetworkMapSpecs struct {
	SharedBypassFlow        *ebpf.MapSpec `ebpf:"shared_bypass_flow"`
	SharedBypassIpv4        *ebpf.MapSpec `ebpf:"shared_bypass_ipv4"`
	SharedBypassIpv6        *ebpf.MapSpec `ebpf:"shared_bypass_ipv6"`
	SharedControl           *ebpf.MapSpec `ebpf:"shared_control"`
	SharedExcludeSourceIpv4 *ebpf.MapSpec `ebpf:"shared_exclude_source_ipv4"`
	SharedExcludeSourceIpv6 *ebpf.MapSpec `ebpf:"shared_exclude_source_ipv6"`
	SharedExcludeSourceMac  *ebpf.MapSpec `ebpf:"shared_exclude_source_mac"`
	SharedFlowByOriginal    *ebpf.MapSpec `ebpf:"shared_flow_by_original"`
	SharedFlowByToken       *ebpf.MapSpec `ebpf:"shared_flow_by_token"`
	SharedHostIpv4          *ebpf.MapSpec `ebpf:"shared_host_ipv4"`
	SharedHostIpv6          *ebpf.MapSpec `ebpf:"shared_host_ipv6"`
	SharedIncludeSourceIpv4 *ebpf.MapSpec `ebpf:"shared_include_source_ipv4"`
	SharedIncludeSourceIpv6 *ebpf.MapSpec `ebpf:"shared_include_source_ipv6"`
	SharedIncludeSourceMac  *ebpf.MapSpec `ebpf:"shared_include_source_mac"`
	SharedScratch           *ebpf.MapSpec `ebpf:"shared_scratch"`
	SharedStats             *ebpf.MapSpec `ebpf:"shared_stats"`
}

// SharedNetworkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SharedNetworkVariableSpecs struct {
}

// SharedNetworkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSharedNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type SharedNetworkObjects struct {
	SharedNetworkPrograms
	SharedNetworkMaps
	SharedNetworkVariables
}

func (o *SharedNetworkObjects) Close() error {
	return _SharedNetworkClose(
		&o.SharedNetworkPrograms,
		&o.SharedNetworkMaps,
	)
}

// SharedNetworkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSharedNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type SharedNetworkMaps struct {
	SharedBypassFlow        *ebpf.Map `ebpf:"shared_bypass_flow"`
	SharedBypassIpv4        *ebpf.Map `ebpf:"shared_bypass_ipv4"`
	SharedBypassIpv6        *ebpf.Map `ebpf:"shared_bypass_ipv6"`
	SharedControl           *ebpf.Map `ebpf:"shared_control"`
	SharedExcludeSourceIpv4 *ebpf.Map `ebpf:"shared_exclude_source_ipv4"`
	SharedExcludeSourceIpv6 *ebpf.Map `ebpf:"shared_exclude_source_ipv6"`
	SharedExcludeSourceMac  *ebpf.Map `ebpf:"shared_exclude_source_mac"`
	SharedFlowByOriginal    *ebpf.Map `ebpf:"shared_flow_by_original"`
	SharedFlowByToken       *ebpf.Map `ebpf:"shared_flow_by_token"`
	SharedHostIpv4          *ebpf.Map `ebpf:"shared_host_ipv4"`
	SharedHostIpv6          *ebpf.Map `ebpf:"shared_host_ipv6"`
	SharedIncludeSourceIpv4 *ebpf.Map `ebpf:"shared_include_source_ipv4"`
	SharedIncludeSourceIpv6 *ebpf.Map `ebpf:"shared_include_source_ipv6"`
	SharedIncludeSourceMac  *ebpf.Map `ebpf:"shared_include_source_mac"`
	SharedScratch           *ebpf.Map `ebpf:"shared_scratch"`
	SharedStats             *ebpf.Map `ebpf:"shared_stats"`
}

func (m *SharedNetworkMaps) Close() error {
	return _SharedNetworkClose(
		m.SharedBypassFlow,
		m.SharedBypassIpv4,
		m.SharedBypassIpv6,
		m.SharedControl,
		m.SharedExcludeSourceIpv4,
		m.SharedExcludeSourceIpv6,
		m.SharedExcludeSourceMac,
		m.SharedFlowByOriginal,
		m.SharedFlowByToken,
		m.SharedHostIpv4,
		m.SharedHostIpv6,
		m.SharedIncludeSourceIpv4,
		m.SharedIncludeSourceIpv6,
		m.SharedIncludeSourceMac,
		m.SharedScratch,
		m.SharedStats,
	)
}

// SharedNetworkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSharedNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type SharedNetworkVariables struct {
}

// SharedNetworkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSharedNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type SharedNetworkPrograms struct {
	SingboxSharedEgress  *ebpf.Program `ebpf:"singbox_shared_egress"`
	SingboxSharedIngress *ebpf.Program `ebpf:"singbox_shared_ingress"`
}

func (p *SharedNetworkPrograms) Close() error {
	return _SharedNetworkClose(
		p.SingboxSharedEgress,
		p.SingboxSharedIngress,
	)
}

func _SharedNetworkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed shared_network_bpfeb.o
var _SharedNetworkBytes []byte
