// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && with_ebpf

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	SpliceMapSplicePeers           = "splice_peers"
	SpliceMapSpliceSockets         = "splice_sockets"
	SpliceMapSpliceStats           = "splice_stats"
	SpliceProgSingboxSpliceParser  = "singbox_splice_parser"
	SpliceProgSingboxSpliceVerdict = "singbox_splice_verdict"
)

// LoadSplice returns the embedded CollectionSpec for Splice.
func LoadSplice() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SpliceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Splice: %w", err)
	}

	return spec, err
}

// LoadSpliceObjects loads Splice and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SpliceObjects
//	*SplicePrograms
//	*SpliceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSpliceObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSplice()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SpliceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SpliceSpecs struct {
	SpliceProgramSpecs
	SpliceMapSpecs
	SpliceVariableSpecs
}

// SpliceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SpliceProgramSpecs struct {
	SingboxSpliceParser  *ebpf.ProgramSpec `ebpf:"singbox_splice_parser"`
	SingboxSpliceVerdict *ebpf.ProgramSpec `ebpf:"singbox_splice_verdict"`
}

// SpliceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SpliceMapSpecs struct {
	SplicePeers   *ebpf.MapSpec `ebpf:"splice_peers"`
	SpliceSockets *ebpf.MapSpec `ebpf:"splice_sockets"`
	SpliceStats   *ebpf.MapSpec `ebpf:"splice_stats"`
}

// SpliceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SpliceVariableSpecs struct {
}

// SpliceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSpliceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SpliceObjects struct {
	SplicePrograms
	SpliceMaps
	SpliceVariables
}

func (o *SpliceObjects) Close() error {
	return _SpliceClose(
		&o.SplicePrograms,
		&o.SpliceMaps,
	)
}

// SpliceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSpliceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SpliceMaps struct {
	SplicePeers   *ebpf.Map `ebpf:"splice_peers"`
	SpliceSockets *ebpf.Map `ebpf:"splice_sockets"`
	SpliceStats   *ebpf.Map `ebpf:"splice_stats"`
}

func (m *SpliceMaps) Close() error {
	return _SpliceClose(
		m.SplicePeers,
		m.SpliceSockets,
		m.SpliceStats,
	)
}

// SpliceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSpliceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SpliceVariables struct {
}

// SplicePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSpliceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SplicePrograms struct {
	SingboxSpliceParser  *ebpf.Program `ebpf:"singbox_splice_parser"`
	SingboxSpliceVerdict *ebpf.Program `ebpf:"singbox_splice_verdict"`
}

func (p *SplicePrograms) Close() error {
	return _SpliceClose(
		p.SingboxSpliceParser,
		p.SingboxSpliceVerdict,
	)
}

func _SpliceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed splice_bpfeb.o
var _SpliceBytes []byte
