// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && with_ebpf

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	TCMapTcAssignment                          = "tc_assignment"
	TCMapTcBypassIpv4                          = "tc_bypass_ipv4"
	TCMapTcBypassIpv6                          = "tc_bypass_ipv6"
	TCMapTcControl                             = "tc_control"
	TCMapTcExcludeSourceIpv4                   = "tc_exclude_source_ipv4"
	TCMapTcExcludeSourceIpv6                   = "tc_exclude_source_ipv6"
	TCMapTcExcludeSourceMac                    = "tc_exclude_source_mac"
	TCMapTcHostIpv4                            = "tc_host_ipv4"
	TCMapTcHostIpv6                            = "tc_host_ipv6"
	TCMapTcIncludeSourceIpv4                   = "tc_include_source_ipv4"
	TCMapTcIncludeSourceIpv6                   = "tc_include_source_ipv6"
	TCMapTcIncludeSourceMac                    = "tc_include_source_mac"
	TCMapTcListenerSockets                     = "tc_listener_sockets"
	TCMapTcLocalBypassPort                     = "tc_local_bypass_port"
	TCMapTcSelfSockets                         = "tc_self_sockets"
	TCMapTcSharedBypassPort                    = "tc_shared_bypass_port"
	TCMapTcUidPolicy                           = "tc_uid_policy"
	TCProgSingboxTcDeliveryIngress             = "singbox_tc_delivery_ingress"
	TCProgSingboxTcDeliveryIngressLegacy       = "singbox_tc_delivery_ingress_legacy"
	TCProgSingboxTcDeliveryIngressUdp          = "singbox_tc_delivery_ingress_udp"
	TCProgSingboxTcLocalEgressEthernetMark     = "singbox_tc_local_egress_ethernet_mark"
	TCProgSingboxTcLocalEgressEthernetProcess  = "singbox_tc_local_egress_ethernet_process"
	TCProgSingboxTcLocalEgressRawIpMark        = "singbox_tc_local_egress_raw_ip_mark"
	TCProgSingboxTcLocalEgressRawIpProcess     = "singbox_tc_local_egress_raw_ip_process"
	TCProgSingboxTcSharedIngressEthernet       = "singbox_tc_shared_ingress_ethernet"
	TCProgSingboxTcSharedIngressEthernetLegacy = "singbox_tc_shared_ingress_ethernet_legacy"
	TCProgSingboxTcSharedIngressEthernetUdp    = "singbox_tc_shared_ingress_ethernet_udp"
	TCProgSingboxTcSharedIngressRawIp          = "singbox_tc_shared_ingress_raw_ip"
	TCProgSingboxTcSharedIngressRawIpLegacy    = "singbox_tc_shared_ingress_raw_ip_legacy"
	TCProgSingboxTcSharedIngressRawIpUdp       = "singbox_tc_shared_ingress_raw_ip_udp"
)

// LoadTC returns the embedded CollectionSpec for TC.
func LoadTC() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TCBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TC: %w", err)
	}

	return spec, err
}

// LoadTCObjects loads TC and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TCObjects
//	*TCPrograms
//	*TCMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTCObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTC()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TCSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCSpecs struct {
	TCProgramSpecs
	TCMapSpecs
	TCVariableSpecs
}

// TCProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCProgramSpecs struct {
	SingboxTcDeliveryIngress             *ebpf.ProgramSpec `ebpf:"singbox_tc_delivery_ingress"`
	SingboxTcDeliveryIngressLegacy       *ebpf.ProgramSpec `ebpf:"singbox_tc_delivery_ingress_legacy"`
	SingboxTcDeliveryIngressUdp          *ebpf.ProgramSpec `ebpf:"singbox_tc_delivery_ingress_udp"`
	SingboxTcLocalEgressEthernetMark     *ebpf.ProgramSpec `ebpf:"singbox_tc_local_egress_ethernet_mark"`
	SingboxTcLocalEgressEthernetProcess  *ebpf.ProgramSpec `ebpf:"singbox_tc_local_egress_ethernet_process"`
	SingboxTcLocalEgressRawIpMark        *ebpf.ProgramSpec `ebpf:"singbox_tc_local_egress_raw_ip_mark"`
	SingboxTcLocalEgressRawIpProcess     *ebpf.ProgramSpec `ebpf:"singbox_tc_local_egress_raw_ip_process"`
	SingboxTcSharedIngressEthernet       *ebpf.ProgramSpec `ebpf:"singbox_tc_shared_ingress_ethernet"`
	SingboxTcSharedIngressEthernetLegacy *ebpf.ProgramSpec `ebpf:"singbox_tc_shared_ingress_ethernet_legacy"`
	SingboxTcSharedIngressEthernetUdp    *ebpf.ProgramSpec `ebpf:"singbox_tc_shared_ingress_ethernet_udp"`
	SingboxTcSharedIngressRawIp          *ebpf.ProgramSpec `ebpf:"singbox_tc_shared_ingress_raw_ip"`
	SingboxTcSharedIngressRawIpLegacy    *ebpf.ProgramSpec `ebpf:"singbox_tc_shared_ingress_raw_ip_legacy"`
	SingboxTcSharedIngressRawIpUdp       *ebpf.ProgramSpec `ebpf:"singbox_tc_shared_ingress_raw_ip_udp"`
}

// TCMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCMapSpecs struct {
	TcAssignment        *ebpf.MapSpec `ebpf:"tc_assignment"`
	TcBypassIpv4        *ebpf.MapSpec `ebpf:"tc_bypass_ipv4"`
	TcBypassIpv6        *ebpf.MapSpec `ebpf:"tc_bypass_ipv6"`
	TcControl           *ebpf.MapSpec `ebpf:"tc_control"`
	TcExcludeSourceIpv4 *ebpf.MapSpec `ebpf:"tc_exclude_source_ipv4"`
	TcExcludeSourceIpv6 *ebpf.MapSpec `ebpf:"tc_exclude_source_ipv6"`
	TcExcludeSourceMac  *ebpf.MapSpec `ebpf:"tc_exclude_source_mac"`
	TcHostIpv4          *ebpf.MapSpec `ebpf:"tc_host_ipv4"`
	TcHostIpv6          *ebpf.MapSpec `ebpf:"tc_host_ipv6"`
	TcIncludeSourceIpv4 *ebpf.MapSpec `ebpf:"tc_include_source_ipv4"`
	TcIncludeSourceIpv6 *ebpf.MapSpec `ebpf:"tc_include_source_ipv6"`
	TcIncludeSourceMac  *ebpf.MapSpec `ebpf:"tc_include_source_mac"`
	TcListenerSockets   *ebpf.MapSpec `ebpf:"tc_listener_sockets"`
	TcLocalBypassPort   *ebpf.MapSpec `ebpf:"tc_local_bypass_port"`
	TcSelfSockets       *ebpf.MapSpec `ebpf:"tc_self_sockets"`
	TcSharedBypassPort  *ebpf.MapSpec `ebpf:"tc_shared_bypass_port"`
	TcUidPolicy         *ebpf.MapSpec `ebpf:"tc_uid_policy"`
}

// TCVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCVariableSpecs struct {
}

// TCObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCObjects struct {
	TCPrograms
	TCMaps
	TCVariables
}

func (o *TCObjects) Close() error {
	return _TCClose(
		&o.TCPrograms,
		&o.TCMaps,
	)
}

// TCMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCMaps struct {
	TcAssignment        *ebpf.Map `ebpf:"tc_assignment"`
	TcBypassIpv4        *ebpf.Map `ebpf:"tc_bypass_ipv4"`
	TcBypassIpv6        *ebpf.Map `ebpf:"tc_bypass_ipv6"`
	TcControl           *ebpf.Map `ebpf:"tc_control"`
	TcExcludeSourceIpv4 *ebpf.Map `ebpf:"tc_exclude_source_ipv4"`
	TcExcludeSourceIpv6 *ebpf.Map `ebpf:"tc_exclude_source_ipv6"`
	TcExcludeSourceMac  *ebpf.Map `ebpf:"tc_exclude_source_mac"`
	TcHostIpv4          *ebpf.Map `ebpf:"tc_host_ipv4"`
	TcHostIpv6          *ebpf.Map `ebpf:"tc_host_ipv6"`
	TcIncludeSourceIpv4 *ebpf.Map `ebpf:"tc_include_source_ipv4"`
	TcIncludeSourceIpv6 *ebpf.Map `ebpf:"tc_include_source_ipv6"`
	TcIncludeSourceMac  *ebpf.Map `ebpf:"tc_include_source_mac"`
	TcListenerSockets   *ebpf.Map `ebpf:"tc_listener_sockets"`
	TcLocalBypassPort   *ebpf.Map `ebpf:"tc_local_bypass_port"`
	TcSelfSockets       *ebpf.Map `ebpf:"tc_self_sockets"`
	TcSharedBypassPort  *ebpf.Map `ebpf:"tc_shared_bypass_port"`
	TcUidPolicy         *ebpf.Map `ebpf:"tc_uid_policy"`
}

func (m *TCMaps) Close() error {
	return _TCClose(
		m.TcAssignment,
		m.TcBypassIpv4,
		m.TcBypassIpv6,
		m.TcControl,
		m.TcExcludeSourceIpv4,
		m.TcExcludeSourceIpv6,
		m.TcExcludeSourceMac,
		m.TcHostIpv4,
		m.TcHostIpv6,
		m.TcIncludeSourceIpv4,
		m.TcIncludeSourceIpv6,
		m.TcIncludeSourceMac,
		m.TcListenerSockets,
		m.TcLocalBypassPort,
		m.TcSelfSockets,
		m.TcSharedBypassPort,
		m.TcUidPolicy,
	)
}

// TCVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCVariables struct {
}

// TCPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCPrograms struct {
	SingboxTcDeliveryIngress             *ebpf.Program `ebpf:"singbox_tc_delivery_ingress"`
	SingboxTcDeliveryIngressLegacy       *ebpf.Program `ebpf:"singbox_tc_delivery_ingress_legacy"`
	SingboxTcDeliveryIngressUdp          *ebpf.Program `ebpf:"singbox_tc_delivery_ingress_udp"`
	SingboxTcLocalEgressEthernetMark     *ebpf.Program `ebpf:"singbox_tc_local_egress_ethernet_mark"`
	SingboxTcLocalEgressEthernetProcess  *ebpf.Program `ebpf:"singbox_tc_local_egress_ethernet_process"`
	SingboxTcLocalEgressRawIpMark        *ebpf.Program `ebpf:"singbox_tc_local_egress_raw_ip_mark"`
	SingboxTcLocalEgressRawIpProcess     *ebpf.Program `ebpf:"singbox_tc_local_egress_raw_ip_process"`
	SingboxTcSharedIngressEthernet       *ebpf.Program `ebpf:"singbox_tc_shared_ingress_ethernet"`
	SingboxTcSharedIngressEthernetLegacy *ebpf.Program `ebpf:"singbox_tc_shared_ingress_ethernet_legacy"`
	SingboxTcSharedIngressEthernetUdp    *ebpf.Program `ebpf:"singbox_tc_shared_ingress_ethernet_udp"`
	SingboxTcSharedIngressRawIp          *ebpf.Program `ebpf:"singbox_tc_shared_ingress_raw_ip"`
	SingboxTcSharedIngressRawIpLegacy    *ebpf.Program `ebpf:"singbox_tc_shared_ingress_raw_ip_legacy"`
	SingboxTcSharedIngressRawIpUdp       *ebpf.Program `ebpf:"singbox_tc_shared_ingress_raw_ip_udp"`
}

func (p *TCPrograms) Close() error {
	return _TCClose(
		p.SingboxTcDeliveryIngress,
		p.SingboxTcDeliveryIngressLegacy,
		p.SingboxTcDeliveryIngressUdp,
		p.SingboxTcLocalEgressEthernetMark,
		p.SingboxTcLocalEgressEthernetProcess,
		p.SingboxTcLocalEgressRawIpMark,
		p.SingboxTcLocalEgressRawIpProcess,
		p.SingboxTcSharedIngressEthernet,
		p.SingboxTcSharedIngressEthernetLegacy,
		p.SingboxTcSharedIngressEthernetUdp,
		p.SingboxTcSharedIngressRawIp,
		p.SingboxTcSharedIngressRawIpLegacy,
		p.SingboxTcSharedIngressRawIpUdp,
	)
}

func _TCClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_bpfel.o
var _TCBytes []byte
